# permissions for end users to view ec2is.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ec2i-viewer-role
rules:
- apiGroups:
  - ec2igroup.ec2idomain
  resources:
  - ec2is
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ec2igroup.ec2idomain
  resources:
  - ec2is/status
  verbs:
  - get
