
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ec2igroup.ec2idomain
  resources:
  - ec2is
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ec2igroup.ec2idomain
  resources:
  - ec2is/status
  verbs:
  - get
  - patch
  - update
